name: {{ app.name.upper_camel }}
options:
  xcodeVersion: 1540
  minimumXcodeGenVersion: 2.39.0
  createIntermediateGroups: true
  generateEmptyDirectories: true
  deploymentTarget:
    iOS: {{ app.deployment_target }}

targets:
  {{ app.name.upper_camel }}:
    type: application
    platform: iOS
    deploymentTarget: {{ app.deployment_target }}
    sources: [{{ app.name.upper_camel }}]
    scheme:
      storeKitConfiguration: {{ app.name.upper_camel }}/Configuration.storekit
    info:
      path: {{ app.name.upper_camel }}/Info.plist
      properties:
        UISupportedInterfaceOrientations: [UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight, UIInterfaceOrientationPortrait]
        UISupportedInterfaceOrientations~ipad: [UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight, UIInterfaceOrientationPortrait, UIInterfaceOrientationPortraitUpsideDown]
        UILaunchScreen:
          UIImageRespectsSafeAreaInsets: NO
        UIApplicationSupportsIndirectInputEvents: YES
        ITSAppUsesNonExemptEncryption: NO
        NSCameraUsageDescription: "We use the camera to take profile pictures and other user controlled actions."
        NSFaceIDUsageDescription: "We use Face ID for secure authentication."
        CFBundleName: {{ app.name.display_name }}
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        CFBundleShortVersionString: "1.0.0"
    settings:
      base:
        DEVELOPMENT_TEAM: {{ app.team_id }}
        PRODUCT_BUNDLE_IDENTIFIER: {{ app.bundle_id }}
        SWIFT_VERSION: 5.10
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        SWIFT_ENABLE_BARE_SLASH_REGEX: YES
        ENABLE_USER_SCRIPT_SANDBOXING: YES
      configs:
        debug:
          CODE_SIGN_IDENTITY: {{ app.code_sign.debug.identity }}
          CODE_SIGNING_REQUIRED: {{ app.code_sign.debug.required }}
          CODE_SIGNING_ALLOWED: {{ app.code_sign.debug.allowed }}
          CODE_SIGN_ENTITLEMENTS: {{ app.name.upper_camel }}/Debug.entitlements
          CODE_SIGN_STYLE: {{ app.code_sign.debug.style }}
          PROVISIONING_PROFILE_SPECIFIER: {{ app.code_sign.debug.profile_specifier }}
        release:
          CODE_SIGN_ENTITLEMENTS: {{ app.name.upper_camel }}/Release.entitlements
          CODE_SIGN_IDENTITY: {{ app.code_sign.release.identity }}
          CODE_SIGNING_REQUIRED: {{ app.code_sign.release.required }}
          CODE_SIGNING_ALLOWED: {{ app.code_sign.release.allowed }}
          CODE_SIGN_STYLE: {{ app.code_sign.debug.style }}
          PROVISIONING_PROFILE_SPECIFIER: {{ app.code_sign.debug.profile_specifier }}
    dependencies:
      - sdk: StoreKit.framework
      - package: Parra
      - package: RevenueCat
        products:
          - RevenueCat
          - RevenueCatUI



schemes:
  {{ app.name.upper_camel }}:
    build:
      targets:
        {{ app.name.upper_camel }}: all
      parallelizeBuild: true
      buildImplicitDependencies: true
    run:
      environmentVariables:
        IDEPreferLogStreaming: YES # Silence warning in Xcode console
    archive:
      preActions:
        - settingsTarget: {{ app.name.upper_camel }}
          name: Parra - Increment project build number
          script: |
            if [ "$ACTION" = "install" ]; then
                echo "Parra - Updating incrementing build number!";
                cd "${PROJECT_DIR}" ; agvtool bump    
            else
                echo "Parra - Not an install build. Skipping incrementing build number."
            fi

            exit 0
