name: {{ app.name.upper_camel }}
options:
  xcodeVersion: 15.4
  minimumXcodeGenVersion: 2.39.0
  createIntermediateGroups: true
  generateEmptyDirectories: true
  deploymentTarget:
    iOS: {{ app.deployment_target }}

targets:
  {{ app.name.upper_camel }}:
    type: application
    platform: iOS
    deploymentTarget: {{ app.deployment_target }}
    sources: [{{ app.name.upper_camel }}]
    info:
      path: {{ app.name.upper_camel }}/Info.plist
      properties:
        UISupportedInterfaceOrientations: [UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight, UIInterfaceOrientationPortrait]
        UISupportedInterfaceOrientations~ipad: [UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight, UIInterfaceOrientationPortrait, UIInterfaceOrientationPortraitUpsideDown]
        UILaunchScreen:
          UIImageRespectsSafeAreaInsets: NO
        UIApplicationSupportsIndirectInputEvents: YES
        ITSAppUsesNonExemptEncryption: NO
        NSCameraUsageDescription: "We use the camera to take profile pictures and other user controlled actions."
        NSFaceIDUsageDescription: "We use Face ID for secure authentication."
    settings:
      base:
        DEVELOPMENT_TEAM: {{ app.team_id }}
        PRODUCT_BUNDLE_IDENTIFIER: {{ app.bundle_id }}
        SWIFT_VERSION: 5.9
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        SWIFT_ENABLE_BARE_SLASH_REGEX: YES
      configs:
        debug:
          CODE_SIGN_IDENTITY: {{ app.code_sign.debug.identity }}
          CODE_SIGNING_REQUIRED: {{ app.code_sign.debug.required }}
          CODE_SIGNING_ALLOWED: {{ app.code_sign.debug.allowed }}
          CODE_SIGN_ENTITLEMENTS: {{ app.name.upper_camel }}/Debug.entitlements
        release:
          CODE_SIGN_ENTITLEMENTS: {{ app.name.upper_camel }}/Release.entitlements
          CODE_SIGN_IDENTITY: {{ app.code_sign.release.identity }}
          CODE_SIGNING_REQUIRED: {{ app.code_sign.release.required }}
          CODE_SIGNING_ALLOWED: {{ app.code_sign.release.allowed }}
    dependencies:
      - package: Parra
