name: {{ app.name }}
options:
  xcodeVersion: 15.3
  minimumXcodeGenVersion: 2.39.0
  createIntermediateGroups: true
  generateEmptyDirectories: true
  deploymentTarget:
    iOS: {{ app.deployment_target }}
targets:
  {{ app.name }}:
    type: application
    platform: iOS
    deploymentTarget: {{ app.deployment_target }}
    sources: [{{ app.name }}]
    info:
      path: {{ app.name }}/Info.plist
      properties:
        UISupportedInterfaceOrientations: [UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight, UIInterfaceOrientationPortrait]
        UISupportedInterfaceOrientations~ipad: [UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight, UIInterfaceOrientationPortrait, UIInterfaceOrientationPortraitUpsideDown]
        UILaunchScreen:
          UIImageRespectsSafeAreaInsets: NO
        UIApplicationSupportsIndirectInputEvents: YES
        ITSAppUsesNonExemptEncryption: NO
        NSCameraUsageDescription: "We use the camera to take profile pictures and other user controlled actions."
        NSFaceIDUsageDescription: "We use Face ID for secure authentication."
    settings:
      base:
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGNING_ALLOWED: NO
        PRODUCT_BUNDLE_IDENTIFIER: {{ app.bundle_id }}
        # DEVELOPMENT_ASSET_PATHS: "\"{{ app.name }}/Preview Content\"" Don't think we need this
        SWIFT_VERSION: 5.9
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        SWIFT_ENABLE_BARE_SLASH_REGEX: YES
      configs:
        debug:
          CODE_SIGN_ENTITLEMENTS: {{ app.name }}/Debug.entitlements
        release:
          CODE_SIGN_ENTITLEMENTS: {{ app.name }}/Release.entitlements
    dependencies:
      - package: Parra

settings:
  CODE_SIGNING_ALLOWED: NO
  base:
    SWIFT_VERSION: 5.9
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    SWIFT_ENABLE_BARE_SLASH_REGEX: YES
  debug:
    CODE_SIGN_IDENTITY: "-"
    CODE_SIGNING_REQUIRED: NO
    CODE_SIGNING_ALLOWED: NO
  release:
    CODE_SIGN_IDENTITY: iPhone Distribution

packages:
  Parra:
    url: https://github.com/Parra-Inc/parra-mobile-sdks
    minorVersion: 0.1.15
