# fastlane/Fastfile
default_platform :ios

platform :ios do
  before_all do
    if ENV["CIRCLECI"]
      setup_circle_ci
    end
  end

  desc "Runs all the tests"
  lane :test do
    run_tests(
        project: "Parra.xcodeproj", 
        devices: ["iPhone 15"],    
        scheme: "TestRunner",
        prelaunch_simulator: true,
        result_bundle: true, # required to gather coverage.
        code_coverage: true
    )
  end
end