import { ExecOptions } from 'child_process';
import Logger from './logger/logger.js';

export type CommandOptions = {
  encoding: BufferEncoding;
  throwForStdErr: boolean;
  commandLogger?: Logger;
} & ExecOptions;

export const DEFAULT_COMMAND_OPTIONS: CommandOptions = {
  encoding: 'utf8',
  maxBuffer: 1024 * 1024 * 100, // 100 MiB
  /// If set, throws if stderr is not empty. Defaults to false. since many commands write
  /// to stderr even when they succeed.
  throwForStdErr: false,
  /// The logger instance to use for logs generated by running commands. Setting this
  /// will also enable logging of the command itself before it is executed.
  commandLogger: undefined,
};
